[chunking]
strategy = "recursive_character_text_splitter"
chunk_size = 1000
chunk_overlap = 200

# strategy = "markdown_splitter"
# headers_to_split_on = ["##", "###", "####", "#####", "######"]
# return_each_line = true
# strip_headers = false

[rag_prompt]
prompt_template = """
Answer the question in the below context:
{context}

Question: {question}
"""
